using System;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;
using Logger = SovereignTowns.Logging.Logger;

namespace SovereignTowns.Parties;

/// <summary>
/// Mod 自定义的"招募队伍"组件。
///
/// 设计要点：
///   - 继承 <see cref="CustomPartyComponent"/>，因此底层已有 _homeSettlement / _owner / _name 等存档字段（id 10/20/30…）；
///     本类自有 [SaveableField(1)] _homeSettlement 仅用于运行时直接访问与冗余存档，
///     vanilla 局部 saveId 不与基类冲突（每个 TypeDefinition 的字段表互相独立）。
///   - HomeSettlement / PartyOwner / Name 重写为动态计算，避免存档后所有者易主时返回过期 Hero。
///   - AvoidHostileActions = true：招募队伍不主动作战；遭遇敌方应交给 vanilla AI 逃跑/被击破。
///   - 创建只走 <see cref="MobileParty.CreateParty(string, PartyComponent)"/>（vanilla CustomPartyComponent 模板路径），
///     不调用 MBObjectManager.CreateObject。
///
/// 关于 TypeDefiner：参见 <see cref="SovereignTowns.SaveSystem.SovereignTownsTypeDefiner"/>。
/// TaleWorlds 通过反射在加载所有 Mod 程序集时自动发现 SaveableTypeDefiner 派生类，
/// 因此**无需**在 SubModule 中显式注册。
/// </summary>
public sealed class RecruitingPartyComponent : CustomPartyComponent
{
    /// <summary>用于 stringId 的固定前缀；后接 settlement.StringId 与 ticks 避免冲突。</summary>
    public const string StringIdPrefix = "st_recruit_";

    /// <summary>vanilla CustomPartyComponent 内部使用的 PartyTemplate stringId。</summary>
    private const string VanillaPartyTemplateStringId = "quest_party_template_1";

    /// <summary>本组件运行时的家园定居点。基类已用 [SaveableField(20)] 存了一份，这里冗余持有便于直接访问。</summary>
    [SaveableField(1)]
    private Settlement? _homeSettlement;

    [SaveableField(2)]
    private int _recruitedThisTrip;

    [SaveableField(3)]
    private Settlement? _assignedTarget;

    [CachedData]
    private TextObject? _cachedName;

    public override Hero? PartyOwner => _homeSettlement?.OwnerClan?.Leader;

    public override TextObject Name
    {
        get
        {
            if (_cachedName != null)
            {
                return _cachedName;
            }

            var settlementName = _homeSettlement?.Name?.ToString() ?? "未知";
            _cachedName = new TextObject("{=ST_RecruitingPartyName}征兵队 - " + settlementName);
            return _cachedName;
        }
    }

    public override Settlement HomeSettlement => _homeSettlement!;

    public override bool AvoidHostileActions => true;

    public int RecruitedThisTrip => _recruitedThisTrip;

    public Settlement? AssignedTarget => _assignedTarget;

    public void RecordRecruited(int count)
    {
        if (count <= 0) return;
        _recruitedThisTrip += count;
    }

    public void SetAssignedTarget(Settlement? target)
    {
        _assignedTarget = target;
    }

    /// <summary>
    /// 私有构造器。只被同类的 <see cref="CreateForTown"/> 工厂调用，
    /// 以及被 vanilla SaveSystem 在加载存档时通过反射实例化（其后 AutoGenerated 字段填充会接管）。
    /// 注意：受 <see cref="CustomPartyComponent.InitializationArgs"/> 是 protected 嵌套类的限制，
    /// 本构造器**不可**为 internal/public（CS0051: Inconsistent accessibility）。
    /// 又因为本类 sealed，protected 会触发 CS0628，故落到 private。
    /// </summary>
    private RecruitingPartyComponent(
        Settlement homeSettlement,
        TextObject name,
        Hero owner,
        string partyMountStringId,
        string partyHarnessStringId,
        float customPartyBaseSpeed,
        bool avoidHostileActions,
        InitializationArgs args,
        Hero? leader = null)
        : base(homeSettlement, name, owner, partyMountStringId, partyHarnessStringId,
               customPartyBaseSpeed, avoidHostileActions, args, leader)
    {
        _homeSettlement = homeSettlement;
    }

    /// <summary>
    /// 创建一个挂靠于指定 Town 的招募队伍，并由该 Town 出资初始化资金。
    /// 任一步失败均返回 null 并记录 Logger.Error，绝不抛异常给调用方。
    /// </summary>
    /// <param name="homeTown">家园城镇（其 Settlement 决定出生位置、所属 Clan、所有者）。</param>
    /// <param name="initialGold">初始拨款金额（从 town 资金扣除）。</param>
    /// <param name="initialTroops">
    /// 可选：用作初始基础护卫的 TroopRoster（已从首府 garrison 抽出）。
    /// null 或空 = 队伍出生空 roster（旧行为）。非 null 时直接进入 InitializationArgs.troops。
    /// </param>
    /// <returns>创建好的 MobileParty；失败返回 null。</returns>
    public static MobileParty? CreateForTown(Town homeTown, int initialGold = 1000, TroopRoster? initialTroops = null)
    {
        if (homeTown == null)
        {
            Logger.Error("RecruitingPartyComponent.CreateForTown: homeTown is null");
            return null;
        }

        try
        {
            var settlement = homeTown.Settlement;
            if (settlement == null)
            {
                Logger.Error("RecruitingPartyComponent.CreateForTown: homeTown.Settlement is null");
                return null;
            }

            var ownerClan = settlement.OwnerClan;
            var ownerLeader = ownerClan?.Leader;
            if (ownerClan == null || ownerLeader == null)
            {
                Logger.Error($"RecruitingPartyComponent.CreateForTown: town '{settlement.StringId}' has no OwnerClan/Leader");
                return null;
            }

            // TroopRoster — 若调用方提供 initialTroops（基础护卫）则使用之；否则空 roster 由后续招募填充
            var startingTroops = initialTroops ?? TroopRoster.CreateDummyTroopRoster();
            var emptyPrisoners = TroopRoster.CreateDummyTroopRoster();

            // 注意：args 必须用 protected 嵌套类 InitializationArgs（继承可访问 protected）
            var args = new InitializationArgs(
                settlement.GatePosition,
                spawnRadius: 1f,
                ownerClan,
                startingTroops,
                emptyPrisoners);

            var nameObj = new TextObject(
                "{=ST_RecruitingPartyName}征兵队 - " + settlement.Name);

            var component = new RecruitingPartyComponent(
                homeSettlement: settlement,
                name: nameObj,
                owner: ownerLeader,
                partyMountStringId: string.Empty,
                partyHarnessStringId: string.Empty,
                customPartyBaseSpeed: 0f,
                avoidHostileActions: true,
                args: args,
                leader: null);

            // 唯一 stringId，避免重复创建冲突
            var stringId = StringIdPrefix
                           + settlement.StringId
                           + "_"
                           + DateTime.UtcNow.Ticks.ToString();

            var mobileParty = MobileParty.CreateParty(stringId, component);
            if (mobileParty == null)
            {
                Logger.Error($"RecruitingPartyComponent.CreateForTown: MobileParty.CreateParty returned null for '{stringId}'");
                return null;
            }
            // B7.22：强制 0 攻击性 — 防自家征兵队主动招惹敌方 / 与玩家产生冲突 dialog
            try { mobileParty.Aggressiveness = 0f; } catch { /* swallow */ }

            // initialGold 参数保留作为契约稳定（B7.27：实际扣费已移到 ModTreasury，不再从城金库注入 party purse）
            // 调用方（RecruitmentManager.TryDispatchRecruiter）已通过 ModTreasury 完成扣费；
            // 此处不再调用 GiveGoldAction.ApplyForSettlementToParty，避免双重扣款。

            Logger.Info(
                $"RecruitingPartyComponent: created '{stringId}' for town '{settlement.StringId}' (owner={ownerLeader.Name}, gold={initialGold})");

            return mobileParty;
        }
        catch (Exception ex)
        {
            Logger.Error(
                $"RecruitingPartyComponent.CreateForTown: unexpected exception for town '{homeTown?.Settlement?.StringId ?? "<null>"}'",
                ex);
            return null;
        }
    }
}
