using System;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;
using Logger = SovereignTowns.Logging.Logger;

namespace SovereignTowns.Parties;

/// <summary>
/// Mod 自定义的“出击队伍”组件 —— 由 home town 派出，意图攻击/拦截 <see cref="TargetParty"/>。
///
/// 设计要点：
///   - 继承 <see cref="CustomPartyComponent"/>，底层已有 _homeSettlement / _owner / _name 等存档字段。
///     本类自有的 _homeSettlement / _targetParty / _departureTime 仅用作运行时直接访问与冗余存档；
///     局部 saveId 1/2/3 与基类不冲突（每个 TypeDefinition 的字段表互相独立）。
///   - HomeSettlement / PartyOwner / Name 重写为基于 _homeSettlement 的动态计算，
///     避免存档加载后所有者易主时返回过期 Hero。
///   - <b>AvoidHostileActions = false</b>：与 Recruiting / Transfer 不同，出击队伍必须主动作战。
///   - 创建只走 <see cref="MobileParty.CreateParty(string, PartyComponent)"/>（vanilla CustomPartyComponent 模板路径），
///     不调用 MBObjectManager.CreateObject。
///   - 区别于 RecruitingPartyComponent：本组件创建时**可选**携带兵员
///     （TroopRoster 由调用方提供，通过 InitializationArgs 触发
///      vanilla 的 InitializeCustomPartyPropertiesWithTroopRoster 路径自动注入）。
///   - <see cref="TargetParty"/> 可空：尚未确定追击目标时由 AI 行为层后续指派。
///
/// 关于 TypeDefiner：参见 <see cref="SovereignTowns.SaveSystem.SovereignTownsTypeDefiner"/>。
/// </summary>
public sealed class SallyForthPartyComponent : CustomPartyComponent
{
    /// <summary>用于 stringId 的固定前缀；后接 settlement.StringId 与 ticks 避免冲突。</summary>
    public const string StringIdPrefix = "st_sallyforth_";

    [SaveableField(1)]
    private Settlement? _homeSettlement;

    [SaveableField(2)]
    private MobileParty? _targetParty;

    [SaveableField(3)]
    private CampaignTime _departureTime;

    [CachedData]
    private TextObject? _cachedName;

    public MobileParty? TargetParty
    {
        get => _targetParty;
        set => _targetParty = value;
    }

    public CampaignTime DepartureTime => _departureTime;

    public override Hero? PartyOwner => _homeSettlement?.OwnerClan?.Leader;

    public override TextObject Name
    {
        get
        {
            if (_cachedName != null)
            {
                return _cachedName;
            }

            var settlementName = _homeSettlement?.Name?.ToString() ?? "未知";
            _cachedName = new TextObject("{=ST_SallyForthPartyName}出击队 - " + settlementName);
            return _cachedName;
        }
    }

    public override Settlement HomeSettlement => _homeSettlement!;

    public override bool AvoidHostileActions => false;

    /// <summary>
    /// 私有构造器。只被同类 <see cref="CreateForTown"/> 工厂调用，
    /// 以及被 vanilla SaveSystem 在加载存档时通过反射实例化（其后 AutoGenerated 字段填充会接管）。
    /// 注意：受 <see cref="CustomPartyComponent.InitializationArgs"/> 是 protected 嵌套类的限制，
    /// 本构造器**不可**为 internal/public（CS0051: Inconsistent accessibility）。
    /// 又因为本类 sealed，protected 会触发 CS0628，故落到 private。
    /// </summary>
    private SallyForthPartyComponent(
        Settlement homeSettlement,
        MobileParty? initialTarget,
        TextObject name,
        Hero owner,
        string partyMountStringId,
        string partyHarnessStringId,
        float customPartyBaseSpeed,
        bool avoidHostileActions,
        InitializationArgs args,
        Hero? leader = null)
        : base(homeSettlement, name, owner, partyMountStringId, partyHarnessStringId,
               customPartyBaseSpeed, avoidHostileActions, args, leader)
    {
        _homeSettlement = homeSettlement;
        _targetParty    = initialTarget;
        _departureTime  = CampaignTime.Now;
    }

    /// <summary>
    /// 创建一支挂靠于指定 Town 的出击队伍，由该 Town 出资初始化资金。
    /// <paramref name="initialTarget"/> 可空（后续由 AI 决策再指派）。
    /// 任一步失败均返回 null 并记录 Logger.Error，绝不抛异常给调用方。
    /// </summary>
    /// <param name="homeTown">家园城镇（其 Settlement 决定出生位置、所属 Clan、所有者）。</param>
    /// <param name="initialTarget">出击目标，可空。</param>
    /// <param name="initialGold">初始拨款金额（从 town 资金扣除）。</param>
    /// <returns>创建好的 MobileParty；失败返回 null。</returns>
    public static MobileParty? CreateForTown(Town homeTown, MobileParty? initialTarget = null, int initialGold = 100)
    {
        if (homeTown == null)
        {
            Logger.Error("SallyForthPartyComponent.CreateForTown: homeTown is null");
            return null;
        }

        try
        {
            var settlement = homeTown.Settlement;
            if (settlement == null)
            {
                Logger.Error("SallyForthPartyComponent.CreateForTown: homeTown.Settlement is null");
                return null;
            }

            var ownerClan = settlement.OwnerClan;
            var ownerLeader = ownerClan?.Leader;
            if (ownerClan == null || ownerLeader == null)
            {
                Logger.Error($"SallyForthPartyComponent.CreateForTown: town '{settlement.StringId}' has no OwnerClan/Leader");
                return null;
            }

            // 空 TroopRoster — 实际士兵由调用方在创建后通过 garrison transfer 添加，
            // 或由后续 AI 决策接入兵员补充
            var emptyTroops    = TroopRoster.CreateDummyTroopRoster();
            var emptyPrisoners = TroopRoster.CreateDummyTroopRoster();

            // 注意：args 必须用 protected 嵌套类 InitializationArgs（继承可访问 protected）
            var args = new InitializationArgs(
                settlement.GatePosition,
                spawnRadius: 1f,
                ownerClan,
                emptyTroops,
                emptyPrisoners);

            var nameObj = new TextObject(
                "{=ST_SallyForthPartyName}出击队 - " + settlement.Name);

            var component = new SallyForthPartyComponent(
                homeSettlement: settlement,
                initialTarget: initialTarget,
                name: nameObj,
                owner: ownerLeader,
                partyMountStringId: string.Empty,
                partyHarnessStringId: string.Empty,
                customPartyBaseSpeed: 0f,
                avoidHostileActions: false,
                args: args,
                leader: null);

            // 唯一 stringId，避免重复创建冲突
            var stringId = StringIdPrefix
                           + settlement.StringId
                           + "_"
                           + DateTime.UtcNow.Ticks.ToString();

            var mobileParty = MobileParty.CreateParty(stringId, component);
            if (mobileParty == null)
            {
                Logger.Error($"SallyForthPartyComponent.CreateForTown: MobileParty.CreateParty returned null for '{stringId}'");
                return null;
            }
            // B7.22：0 攻击性 — sally 仍会攻击指定 target（通过 SetMoveGoToPoint），但不会半路追散兵
            try { mobileParty.Aggressiveness = 0f; } catch { /* swallow */ }

            // initialGold 参数保留作为契约稳定（B7.27：实际扣费已移到 ModTreasury，不再从城金库注入 party purse）
            // 调用方（SallyForthManager.TryCreateSallyParty）已通过 ModTreasury 完成扣费；
            // 此处不再调用 GiveGoldAction.ApplyForSettlementToParty，避免双重扣款。

            var targetDesc = initialTarget?.Name?.ToString() ?? "<none>";
            Logger.Info(
                $"SallyForthPartyComponent: created '{stringId}' for town '{settlement.StringId}' (owner={ownerLeader.Name}, target={targetDesc}, gold={initialGold})");

            return mobileParty;
        }
        catch (Exception ex)
        {
            Logger.Error(
                $"SallyForthPartyComponent.CreateForTown: unexpected exception for town '{homeTown?.Settlement?.StringId ?? "<null>"}'",
                ex);
            return null;
        }
    }
}
