using System;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;
using Logger = SovereignTowns.Logging.Logger;

namespace SovereignTowns.Parties;

/// <summary>
/// Mod 自定义的"调拨队伍"组件 —— 负责把驻军/兵员从 source settlement 运送到 destination settlement。
///
/// 设计要点：
///   - 继承 <see cref="CustomPartyComponent"/>，底层已有 _homeSettlement / _owner / _name 等存档字段。
///     本类自有的 _source / _destination / _departureTime 仅用作运行时直接访问与冗余存档；
///     局部 saveId 1/2/3 与基类不冲突（每个 TypeDefinition 的字段表互相独立）。
///   - HomeSettlement / PartyOwner / Name 重写为基于 _source 的动态计算，
///     避免存档加载后所有者易主时返回过期 Hero。
///   - AvoidHostileActions = true：调拨队伍不主动作战；遭遇敌方应交给 vanilla AI 逃跑/被击破。
///   - 创建只走 <see cref="MobileParty.CreateParty(string, PartyComponent)"/>（vanilla CustomPartyComponent 模板路径），
///     不调用 MBObjectManager.CreateObject。
///   - 区别于 RecruitingPartyComponent：本组件创建时**必须**带上真实兵员
///     （TroopRoster 由调用方提供，通过 InitializationArgs 触发
///      vanilla 的 InitializeCustomPartyPropertiesWithTroopRoster 路径自动注入）。
///
/// 关于 TypeDefiner：参见 <see cref="SovereignTowns.SaveSystem.SovereignTownsTypeDefiner"/>。
/// </summary>
public sealed class TransferPartyComponent : CustomPartyComponent
{
    /// <summary>用于 stringId 的固定前缀；后接 source/destination StringId 与 ticks 避免冲突。</summary>
    public const string StringIdPrefix = "st_transfer_";

    [SaveableField(1)]
    private Settlement? _source;

    [SaveableField(2)]
    private Settlement? _destination;

    [SaveableField(3)]
    private CampaignTime _departureTime;

    [CachedData]
    private TextObject? _cachedName;

    public Settlement? Source => _source;

    public Settlement? Destination => _destination;

    public CampaignTime DepartureTime => _departureTime;

    public override Hero? PartyOwner => _source?.OwnerClan?.Leader;

    public override TextObject Name
    {
        get
        {
            if (_cachedName != null)
            {
                return _cachedName;
            }

            var sourceName = _source?.Name?.ToString() ?? "未知";
            var destName   = _destination?.Name?.ToString() ?? "未知";
            _cachedName = new TextObject(
                "{=ST_TransferPartyName}调拨队 " + sourceName + " → " + destName);
            return _cachedName;
        }
    }

    public override Settlement HomeSettlement => _source!;

    public override bool AvoidHostileActions => true;

    /// <summary>
    /// 私有构造器。只被同类 <see cref="CreateForRoute"/> 工厂调用，
    /// 以及被 vanilla SaveSystem 在加载存档时通过反射实例化（其后 AutoGenerated 字段填充会接管）。
    /// 注意：受 <see cref="CustomPartyComponent.InitializationArgs"/> 是 protected 嵌套类的限制，
    /// 本构造器**不可**为 internal/public（CS0051: Inconsistent accessibility）。
    /// 又因为本类 sealed，protected 会触发 CS0628，故落到 private。
    /// </summary>
    private TransferPartyComponent(
        Settlement source,
        Settlement destination,
        TextObject name,
        Hero owner,
        string partyMountStringId,
        string partyHarnessStringId,
        float customPartyBaseSpeed,
        bool avoidHostileActions,
        InitializationArgs args,
        Hero? leader = null)
        : base(source, name, owner, partyMountStringId, partyHarnessStringId,
               customPartyBaseSpeed, avoidHostileActions, args, leader)
    {
        _source         = source;
        _destination    = destination;
        _departureTime  = CampaignTime.Now;
    }

    /// <summary>
    /// 工厂：从 <paramref name="source"/> 创建一支调拨队伍，
    /// 携带 <paramref name="transferRoster"/> 中指定的兵员，前往 <paramref name="destination"/>。
    /// 任一步失败均返回 null 并记录 Logger.Error，绝不抛异常给调用方。
    /// </summary>
    /// <param name="source">出发定居点（其 OwnerClan/Leader 决定所属与所有者）。</param>
    /// <param name="destination">目的定居点。</param>
    /// <param name="transferRoster">要随队伍带走的真实兵员 roster（不可为空、应含真实士兵）。</param>
    /// <returns>创建好的 MobileParty；失败返回 null。</returns>
    public static MobileParty? CreateForRoute(
        Settlement source,
        Settlement destination,
        TroopRoster transferRoster)
    {
        if (source == null)
        {
            Logger.Error("TransferPartyComponent.CreateForRoute: source is null");
            return null;
        }

        if (destination == null)
        {
            Logger.Error("TransferPartyComponent.CreateForRoute: destination is null");
            return null;
        }

        if (transferRoster == null)
        {
            Logger.Error(
                $"TransferPartyComponent.CreateForRoute: transferRoster is null (source='{source.StringId}', dest='{destination.StringId}')");
            return null;
        }

        try
        {
            var ownerClan   = source.OwnerClan;
            var ownerLeader = ownerClan?.Leader;
            if (ownerClan == null || ownerLeader == null)
            {
                Logger.Error(
                    $"TransferPartyComponent.CreateForRoute: source '{source.StringId}' has no OwnerClan/Leader");
                return null;
            }

            // 调拨队伍不携带俘虏
            var emptyPrisoners = TroopRoster.CreateDummyTroopRoster();

            // 关键：把 transferRoster 直接传给 InitializationArgs，
            // vanilla CustomPartyComponent 构造路径会通过
            // InitializeCustomPartyPropertiesWithTroopRoster 自动把士兵注入 MobileParty.MemberRoster。
            var args = new InitializationArgs(
                source.GatePosition,
                spawnRadius: 1f,
                ownerClan,
                transferRoster,
                emptyPrisoners);

            var nameObj = new TextObject(
                "{=ST_TransferPartyName}调拨队 " + source.Name + " → " + destination.Name);

            var component = new TransferPartyComponent(
                source: source,
                destination: destination,
                name: nameObj,
                owner: ownerLeader,
                partyMountStringId: string.Empty,
                partyHarnessStringId: string.Empty,
                customPartyBaseSpeed: 0f,
                avoidHostileActions: true,
                args: args,
                leader: null);

            // 唯一 stringId：前缀 + source + dest + ticks，避免重复创建冲突
            var stringId = StringIdPrefix
                           + source.StringId
                           + "_"
                           + destination.StringId
                           + "_"
                           + DateTime.UtcNow.Ticks.ToString();

            var mobileParty = MobileParty.CreateParty(stringId, component);
            if (mobileParty == null)
            {
                Logger.Error(
                    $"TransferPartyComponent.CreateForRoute: MobileParty.CreateParty returned null for '{stringId}'");
                return null;
            }
            // B7.22：0 攻击性，避免自家调拨队主动战斗 / 与玩家冲突
            try { mobileParty.Aggressiveness = 0f; } catch { /* swallow */ }

            Logger.Info(
                $"TransferPartyComponent: created '{stringId}' (source='{source.StringId}', dest='{destination.StringId}', troops={transferRoster.TotalManCount})");

            return mobileParty;
        }
        catch (Exception ex)
        {
            Logger.Error(
                $"TransferPartyComponent.CreateForRoute: unexpected exception (source='{source?.StringId ?? "<null>"}', dest='{destination?.StringId ?? "<null>"}')",
                ex);
            return null;
        }
    }
}
